apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm-exporter
  namespace: nvidia-dcgm-exporter
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: nvidia-dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9400
      targetPort: 9400
      protocol: TCP
  selector:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: nvidia-dcgm-exporter
    app.kubernetes.io/component: dcgm-exporter
