apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/v1.19.2
  - cluster-issuer.yaml
  - servicemonitors.yaml
generators:
  - google-cloud-dns-secret-generator.yaml
