apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/piraeus-operator/v2.10.4
patches:
  - target:
      kind: ConfigMap
      name: piraeus-operator-image-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: piraeus-operator-image-config
      data:
        1_override_images.yaml: |
          ---
          base: quay.io/piraeusdatastore
          components:
            linstor-controller:
              image: piraeus-server
              tag: v1.33.1
            linstor-satellite:
              image: piraeus-server
              tag: v1.33.1
