apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - loki-config.yaml
  - loki.yaml
  - loki-servicemonitor.yaml
  - cilium-servicemonitors.yaml
  - etcd-servicemonitor.yaml
  - oauth2-proxy-prometheus.yaml
  - oauth2-proxy-alertmanager.yaml
configMapGenerator:
  - name: grafana-dashboard-etcd-custom
    files:
      - dashboards/etcd.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-cert-manager-custom
    files:
      - dashboards/cert-manager.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-nvidia-dcgm
    files:
      - dashboards/nvidia-dcgm.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-nvidia-gpu-metrics
    files:
      - dashboards/nvidia-gpu-metrics.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-cilium-hubble
    files:
      - dashboards/cilium-hubble.json
    options:
      labels:
        grafana_dashboard: "1"
generators:
  - grafana-oidc-secret-generator.yaml
  - oauth2-proxy-secrets-generator.yaml
