apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - loki-config.yaml
  - loki.yaml
  - loki-servicemonitor.yaml
  - cilium-servicemonitors.yaml
  - oauth2-proxy-prometheus.yaml
  - oauth2-proxy-alertmanager.yaml
generators:
  - grafana-oidc-secret-generator.yaml
  - oauth2-proxy-secrets-generator.yaml
