apiVersion: v1
kind: Service
metadata:
  name: prometheus-remote-write-internal
  namespace: monitoring
  labels:
    app: prometheus-remote-write-internal
  annotations:
    metallb.io/address-pool: homelab
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.73
  loadBalancerSourceRanges:
    - 192.168.2.0/24
    - 10.0.0.0/8
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: monitoring-kube-prometheus-prometheus
