apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    monitoring: default
spec:
  version: v3.9.1
  replicas: 1
  serviceAccountName: prometheus
  externalLabels:
    cluster: homelab
  enableFeatures:
    - endpoint-slice
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  serviceMonitorSelector:
    matchLabels:
      monitoring: default
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      monitoring: default
  ruleNamespaceSelector: {}
  retention: 15d
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: linstor-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
