apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../base/prometheus-operator/v0.87.1
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus.yaml
  - alertmanager-config.yaml
  - alertmanager.yaml
  - grafana-pvc.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-providers.yaml
  - grafana-dashboards.yaml
  - grafana.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - servicemonitors.yaml
  - kube-apiserver-servicemonitor.yaml
  - kubelet-servicemonitor.yaml
  - prometheus-rules.yaml
